[project]
name = "delve_common"
version = "0.0.1"
authors = [
  {name = "Alex Lohnes", email = "alexanderjlohnes@gmail.com"},
]
dependencies = [
  "starlette",
  "fastapi",
  "pydantic",
  "motor"
]
readme = "readme.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"